# Generated by Django 3.0.8 on 2020-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(verbose_name='Имя пользователя', max_length = 20)),
                ('l_country', models.CharField(verbose_name='Страна пользователя', max_length = 56)),
                ('l_city', models.CharField(verbose_name='Город пользователя', max_length = 50)),
                ('l_street', models.CharField(verbose_name='Улица пользователя', max_length = 50)),
                ('phone_number', models.IntegerField(verbose_name='Телефон пользователя')),
            ],
        ),
    ]
