# Generated by Django 3.0.8 on 2020-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200728_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('l_country', models.CharField(max_length=56, verbose_name='Страна пользователя')),
                ('l_city', models.CharField(max_length=50, verbose_name='Город пользователя')),
                ('l_street', models.CharField(max_length=50, verbose_name='Улица пользователя')),
                ('phone_number', models.IntegerField(verbose_name='Телефон пользователя')),
            ],
            options={
                'verbose_name': 'Адресные книги',
                'verbose_name_plural': 'Адресная книга',
            },
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
