# Generated by Django 3.0.8 on 2020-07-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200729_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=100, upload_to='foto', width_field=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.adress')),
            ],
        ),
    ]
