# Generated by Django 3.0.8 on 2020-07-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200729_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.adress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
