# Generated by Django 3.0.8 on 2020-07-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200729_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото пользователя ', 'verbose_name_plural': 'Фотографии пользователя'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img',
        ),
    ]
