# Generated by Django 3.0.8 on 2020-07-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200729_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
