# Generated by Django 3.0.8 on 2020-07-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20200729_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото пользователя', 'verbose_name_plural': 'Фотографии пользователя'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='second_name',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.adress'),
        ),
    ]
