# Generated by Django 3.0.8 on 2020-07-29 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20200729_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адресная книга', 'verbose_name_plural': 'Адресные книги'},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
